// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace OnebrbApiClient.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class CategoryServiceModelICollectionBaseApiResponse
    {
        /// <summary>
        /// Initializes a new instance of the
        /// CategoryServiceModelICollectionBaseApiResponse class.
        /// </summary>
        public CategoryServiceModelICollectionBaseApiResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// CategoryServiceModelICollectionBaseApiResponse class.
        /// </summary>
        public CategoryServiceModelICollectionBaseApiResponse(int? statusCode = default(int?), string message = default(string), IList<CategoryServiceModel> body = default(IList<CategoryServiceModel>))
        {
            StatusCode = statusCode;
            Message = message;
            Body = body;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "statusCode")]
        public int? StatusCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "message")]
        public string Message { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "body")]
        public IList<CategoryServiceModel> Body { get; set; }

    }
}
