// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace OnebrbApiClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ItemRequestModel
    {
        /// <summary>
        /// Initializes a new instance of the ItemRequestModel class.
        /// </summary>
        public ItemRequestModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ItemRequestModel class.
        /// </summary>
        public ItemRequestModel(string title = default(string), string description = default(string), double? price = default(double?), int? categoryId = default(int?), string userId = default(string))
        {
            Title = title;
            Description = description;
            Price = price;
            CategoryId = categoryId;
            UserId = userId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "title")]
        public string Title { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "description")]
        public string Description { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "price")]
        public double? Price { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "categoryId")]
        public int? CategoryId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "userId")]
        public string UserId { get; set; }

    }
}
