// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace OnebrbApiClient.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class ItemServiceModel
    {
        /// <summary>
        /// Initializes a new instance of the ItemServiceModel class.
        /// </summary>
        public ItemServiceModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ItemServiceModel class.
        /// </summary>
        public ItemServiceModel(int? id = default(int?), string title = default(string), string description = default(string), double? price = default(double?), int? categoryId = default(int?), string categoryName = default(string), string userId = default(string), string userFirstName = default(string), string userLastName = default(string), string userEmail = default(string), IList<Rating> ratings = default(IList<Rating>))
        {
            Id = id;
            Title = title;
            Description = description;
            Price = price;
            CategoryId = categoryId;
            CategoryName = categoryName;
            UserId = userId;
            UserFirstName = userFirstName;
            UserLastName = userLastName;
            UserEmail = userEmail;
            Ratings = ratings;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public int? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "title")]
        public string Title { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "description")]
        public string Description { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "price")]
        public double? Price { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "categoryId")]
        public int? CategoryId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "categoryName")]
        public string CategoryName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "userId")]
        public string UserId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "userFirstName")]
        public string UserFirstName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "userLastName")]
        public string UserLastName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "userEmail")]
        public string UserEmail { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ratings")]
        public IList<Rating> Ratings { get; set; }

    }
}
