// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace OnebrbApiClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class RateItemRequestModel
    {
        /// <summary>
        /// Initializes a new instance of the RateItemRequestModel class.
        /// </summary>
        public RateItemRequestModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the RateItemRequestModel class.
        /// </summary>
        public RateItemRequestModel(int? itemId = default(int?), string userId = default(string), string securityHash = default(string))
        {
            ItemId = itemId;
            UserId = userId;
            SecurityHash = securityHash;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "itemId")]
        public int? ItemId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "userId")]
        public string UserId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "securityHash")]
        public string SecurityHash { get; set; }

    }
}
