// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace OnebrbApiClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class Rating
    {
        /// <summary>
        /// Initializes a new instance of the Rating class.
        /// </summary>
        public Rating()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Rating class.
        /// </summary>
        public Rating(int? ratingId = default(int?), int? itemId = default(int?), Item item = default(Item), string userId = default(string), User user = default(User), int? value = default(int?))
        {
            RatingId = ratingId;
            ItemId = itemId;
            Item = item;
            UserId = userId;
            User = user;
            Value = value;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ratingId")]
        public int? RatingId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "itemId")]
        public int? ItemId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "item")]
        public Item Item { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "userId")]
        public string UserId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "user")]
        public User User { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public int? Value { get; set; }

    }
}
