// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace OnebrbApiClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class RatingServiceModel
    {
        /// <summary>
        /// Initializes a new instance of the RatingServiceModel class.
        /// </summary>
        public RatingServiceModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the RatingServiceModel class.
        /// </summary>
        public RatingServiceModel(int? itemId = default(int?), int? value = default(int?))
        {
            ItemId = itemId;
            Value = value;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "itemId")]
        public int? ItemId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public int? Value { get; set; }

    }
}
